package com.example.shared_library

enum class Screen(val screenName: String) {
    screenNotInitialized("screen not initialized"),
    splash("splash"),
    webView("webview"),
    home("home"),
    catalogue("catalogue"),
    catalogueServicesTab("catalogue 'Services' tab"),
    cataloguePersonalTab("catalogue 'Personal' tab"),
    offersList("offers list"),
    offersListAllTab("offers list 'All' tab"),
    offersListCashbackTab("offers list 'Cashback' tab"),
    offersListBonusTab("offers list 'Bonus' tab"),
    offersListFavoriteTab("offers list 'Favorite' tab"),
    offersListPersonalTab("offers list 'Personal' tab"),
    partnersList("partners list"),
    partnersListAllTab("partners list 'All' tab"),
    partnersListCashbackTab("partners list 'Cashback' tab"),
    partnersListBonusTab("partners list 'Bonus' tab"),
    partnersListGiftTab("partners list 'Gift' tab"),
    partnersListFuelTab("partners list 'Fuel' tab"),
    partnersListFavoriteTab("partners list 'Favorite' tab"),
    giftCardList("gift cards list"),
    fuelCardList("fuel cards list"),
    receivedGiftCardTab("received 'Gift' card tab"),
    receivedBonusCardTab("received 'Bonus' card tab"),
    receivedFuelCardTab("received 'Fuel' card tab"),
    story("story"),
    card("card"),
    fuelCardInfo("fuel card info"),
    fuelCardBranches("fuel card branches"),
    fuelMapBranches("fuel map branches"),
    bonusCardInfo("bonus card info"),
    giftCardInfo("gift card info"),
    giftCardHistory("gift card history"),
    bonusCardHistory("bonus card history"),
    fuelCardHistory("fuel card history"),
    filter("filter"),
    partnerInfo("partner info"),
    partnerOffers("partner offers"),
    partnerGallery("partner gallery"),
    partnerGiftCards("partner gift cards"),
    partnerBranches("partner branches"),
    partnerFuel("partner fuel"),
    partnerFindUs("partner find us"),
    partnerBrands("partner brands"),
    infoPopup("info popup"),
    partnerFilterResult("partner filter result"),
    offerFilterResult("offer filter result"),
    offer("offer"),
    settings("settings"),
    buyGiftCardInput("buy gift card"),
    buyGiftCardResult("buy gift card result"),
    buyFuelCardInput("buy fuel card input"),
    qrScanner("qr scanner"),
    paymentMethod("payment method"),
    paymentSources("payment sources"),
    profile("profile"),
    dealHistory("deal history"),
    dealHistoryAllTab("deal history 'All' tab"),
    dealHistoryPinnedTab("deal history 'Pinned' tab"),
    dealHistoryFilter("deal history filter"),
    dealHistorySource("deal history source"),
    dealHistoryCCM("deal history CCM"),
    notification("notifications"),
    accountSwitchingPopup("account switching popup"),
    pinCodeInput("pin code input"),
    pinCodeRecoveryMethods("pin code recovery methods"),
    pinCodeReset("pin code reset"),
    changePinCode("pin code change"),
    security("security"),
    profileAdditionalPhone("profile additional phone"),
    profileAdditionalEmail("profile additional email"),
    profilePhoneEmailVerificationCode("profile phone/email verification code"),
    fuelCardSharedContacts("fuel card shared contacts"),
    tutorial("tutorial"),
    profileAvatars("profile avatars"),
    contactUs("contact us"),
    cardTutorial("card tutorial"),
    receivedCardInfoLoginPopup("received card info login popup"),
    loginMethods("login methods"),
    loginPhoneInput("login phone input"),
    loginVerificationCode("login verification code input"),
    loginPinCodeSetup("login pin code setup"),
    loginPinCodeInput("login pin code input"),
    loginBiometricId("login biometricId"),
    loginSMSTimer("login sms timer"),
    sellBonusCard("sell bonus card"),
    bonusAuction("bonus auction"),
    bonusAuctionSellTab("bonus auction 'Sell' tab"),
    bonusAuctionBuyTab("bonus auction 'Buy' tab"),
    bonusAuctionWishlist("bonus auction 'Wishlist' tab"),
    bonusAuctionSellFilterResult("bonus auction sell filter result"),
    bonusAuctionBuyFilterResult("bonus auction buy filter result"),
    bonusAuctionWishlistFilterResult("bonus auction wishlist filter result"),
    relatedPartnerMerchants("related partner merchants"),
    partnerAuction("partner auction"),
    buyCards("buy cards"),
    idCoinWalletInfo("id coin wallet info"),
    idCoinWalletHistory("id coin wallet history");
}
